### ISSUE TITLE
Support federation

### ISSUE THREAD

**Issue by cweiske** [aaronpk/IndieAuth-MediaWiki#6]
Instead of hard-coding indieauth.com, proper federation should be supported. The user's preferred indieauth server should be used. indieauth.com should only be used as fallback for rel-me login.

**Comment by aaronpk** [comment]
This is exactly the reason I regret naming indieauth.com "indieauth.com".

I have no plans to integrate native IndieAuth protocol support into the wiki plugin. The wiki plugin delegates authentication handling to the server in the config file. This is the "IndieAuth for Developers" use of indieauth.com.

indieauth.com itself does support the IndieAuth protocol, and will use the user's configured authorization endpoint. The reason for the wiki delegating this out to indieauth.com is that I don't want to build all the necessary UX and error handling into the wiki plugin.

This will hopefully be less confusing once I settle on a new name for this use of indieauth.com.
